version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 25
    groups:
      next-core:
        patterns:
          - "next"
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
        update-types:
          - "minor"
          - "patch"
      typescript-eslint:
        patterns:
          - "typescript"
          - "@typescript-eslint/*"
          - "eslint"
          - "eslint-*"
        update-types:
          - "minor"
          - "patch"
      build-tools:
        patterns:
          - "turbopack"
          - "@turbo/*"
          - "tsup"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
      - "spot"
